# Generated by Django 5.1.3 on 2024-12-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="accepted",
            new_name="rejected",
        ),
    ]
