# Generated by Django 5.1.3 on 2024-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.CharField(max_length=2),
        ),
    ]
